kind: pipeline
name: pre-inspection-portal-ui

steps:
- name: build
  image: node
  commands:
  - npm install -g @angular/cli
  - npm audit fix
  - ng build --prod --build-optimizer
- name: deploy
  image: cschlosser/drone-ftps
  environment:
    FTP_USERNAME:
      from_secret: username
    FTP_PASSWORD:
      from_secret: password
    PLUGIN_HOSTNAME:
      from_secret: ftphostname
    PLUGIN_DEST_DIR: /
    PLUGIN_SRC_DIR: /dist/
    PLUGIN_SECURE: true
    PLUGIN_VERIFY: false
# - name: e2e
#   image: node
#   commands:
#   - npm install
#   - ng e2e

trigger:
  branch:
  - master